name: cd

on:
    workflow_run:
        workflows: ['ci']
        types:
            - completed

jobs:
    cd:
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to Development Server
              if: github.event.workflow_run.head_branch == 'dev'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  port: 22
                  script: |
                      # Pull the latest Development Docker image
                      docker pull ${{ secrets.DOCKER_USERNAME }}/bhakti-portfolio-app-dev:latest

                      # Navigate to the application directory
                      cd ~/app/bhakti-portfolio/bhakti-portfolio-app-dev
                      git pull origin dev

                      # Update the .env file
                      rm -f .env.dev
                      echo "VITE_BHAKTI_PORTFOLIO_API_URL=${{ secrets.DEV_VITE_BHAKTI_PORTFOLIO_API_URL }}" >> .env.dev

                      # Restart the Docker container with the new image
                      docker-compose -f docker/docker-compose.dev.yml up -d --force-recreate

                      # Clean up unused Docker resources
                      docker system prune -a -f

            - name: Deploy to Production Server
              if: github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'staging'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  port: 22
                  script: |
                      # Pull the latest Production Docker image
                      docker pull ${{ secrets.DOCKER_USERNAME }}/bhakti-portfolio-app:latest

                      # Navigate to the application directory
                      cd ~/app/bhakti-portfolio/bhakti-portfolio-app
                      git pull origin main

                      # Update the .env file
                      rm -f .env.prod
                      echo "VITE_BHAKTI_PORTFOLIO_API_URL=${{ secrets.PROD_VITE_BHAKTI_PORTFOLIO_API_URL }}" >> .env.prod

                      # Restart the Docker container with the new image
                      docker-compose -f docker/docker-compose.prod.yml up -d --force-recreate

                      # Clean up unused Docker resources
                      docker system prune -a -f
