name: cd

on:
    push:
        branches:
            - main
            - staging
            - dev
    pull_request:
        branches:
            - main
            - staging
            - dev

jobs:
    cd:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Dev Deployment
              if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/dev') || (github.event_name == 'pull_request' && github.base_ref == 'dev') }}
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  port: 22
                  script: |
                      cd ~/app/bhakti-portfolio/bhakti-portfolio-app-dev
                      git pull origin dev
                      rm -f .env
                      echo "VITE_BHAKTI_PORTFOLIO_API_URL=${{ secrets.DEV_VITE_BHAKTI_PORTFOLIO_API_URL }}" >> .env
                      docker-compose -f docker/docker-compose.dev.yml --no-cache && docker-compose -f docker/docker-compose.dev.yml up -d --force-recreate
                      docker system prune -a -f

            - name: Prod Deployment
              if: ${{ (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')) || (github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'staging')) }}
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  port: 22
                  script: |
                      cd ~/app/bhakti-portfolio/bhakti-portfolio-app
                      git pull origin main
                      rm -f .env
                      echo "VITE_BHAKTI_PORTFOLIO_API_URL=${{ secrets.PROD_VITE_BHAKTI_PORTFOLIO_API_URL }}" >> .env
                      docker-compose -f docker/docker-compose.prod.yml build --no-cache && docker-compose -f docker/docker-compose.prod.yml up -d --force-recreate
                      docker system prune -a -f
