name: ci

on:
    push:
        branches:
            - main
            - staging
            - dev
    pull_request:
        branches:
            - main
            - staging

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - name: Install dependencies
              run: npm install

            - name: Build application
              run: npm run build

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Development Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/bhakti-portfolio-app-dev:latest -f docker/dockerfile .
                  docker push ${{ secrets.DOCKER_USERNAME }}/bhakti-portfolio-app-dev:latest

            - name: Build and push Production Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/bhakti-portfolio-app:latest -f docker/dockerfile .
                  docker push ${{ secrets.DOCKER_USERNAME }}/bhakti-portfolio-app:latest
